### GENERAL LOADS

eval "$(fnm env --use-on-cd --shell zsh)"
if [[ -r "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh" ]]; then
  source "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh"
fi

### OHMYZSH

## EXPORTS
export PATH=$HOME/bin:$HOME/.local/bin:/usr/local/bin:$PATH
export ZSH="$HOME/.oh-my-zsh"
export PYTHONPATH="$HOME/dev"
export GOPATH="$HOME/.go"
export SDL_VIDEODRIVER=wayland

## STYLES
zstyle ':omz:update' mode auto      # update automatically without asking
zstyle ':omz:update' frequency 13
zstyle ':completion:*:*:docker:*' option-stacking yes
zstyle ':completion:*:*:docker-*:*' option-stacking yes

## OPTIONS
# CASE_SENSITIVE="true"
# HYPHEN_INSENSITIVE="true"
ZSH_THEME="powerlevel10k/powerlevel10k"
DISABLE_AUTO_TITLE="true"
COMPLETION_WAITING_DOTS="true"
DISABLE_UNTRACKED_FILES_DIRTY="true"
HISTSIZE=500000
SAVEHIST=500000
HIST_STAMPS="dd/mm/yyyy"

setopt EXTENDED_HISTORY
setopt HIST_EXPIRE_DUPS_FIRST
setopt HIST_FIND_NO_DUPS
setopt HIST_IGNORE_ALL_DUPS
setopt HIST_IGNORE_DUPS
setopt HIST_IGNORE_SPACE
setopt HIST_SAVE_NO_DUPS
setopt SHARE_HISTORY

## PLUGINS
plugins=(git caniuse zsh-autosuggestions zsh-syntax-highlighting zsh-completions you-should-use docker aliases zoxide archlinux deno eza fzf gh github fnm ssh-agent)

## LOAD
source $ZSH/oh-my-zsh.sh
if [ -n "${GHOSTTY_RESOURCES_DIR}" ]; then
    builtin source ${GHOSTTY_RESOURCES_DIR}/shell-integration/zsh/ghostty-integration
fi
### OTHERS

## ENV
export LANG=es_ES.UTF-8
if [[ -n $SSH_CONNECTION ]]; then
   export EDITOR='nvim'
else
   export EDITOR='code'
fi

## ALIASES
alias src='source ~/.zshrc' 
alias gt='cd $(xplr)'
alias coded='code $(xplr)'
alias code='code'
alias lk='cd $(walk --icons --preview)'
alias cat='bat'
alias ccat='/usr/bin/cat'
alias ga='git add'
alias gap='ga --patch'
alias gb='git branch'
alias gba='gb --all'
alias gc='git commit'
alias gca='gc --amend --no-edit'
alias gce='gc --amend'
alias gco='git checkout'
alias gcl='git clone --recursive'
alias gd='git diff --output-indicator-new=" " --output-indicator-old=" "'
alias gds='gd --staged'
alias gi='git init'
alias gl='git log --graph --all --pretty=format:"%C(magenta)%h %C(white) %an  %ar%C(blue)  %D%n%s%n"'
alias gm='git merge'
alias gn='git checkout -b'  # new branch
alias gp='git push'
alias gr='git reset'
alias gs='git status --short'
alias gu='git pull'

[[ ! -f ~/.p10k.zsh ]] || source ~/.p10k.zsh
zstyle :omz:plugins:ssh-agent agent-forwarding on
zstyle :omz:plugins:ssh-agent identities id_rsa id_ed25519 work ansible

## BINDKEYS
toggle_sudo() {
  if [[ $BUFFER =~ ^\s*sudo\  ]]; then
    BUFFER=${BUFFER#sudo }  # Remove sudo
  else
    BUFFER="sudo $BUFFER"  # Prepend sudo
  fi
  CURSOR=$#BUFFER  # Move cursor to end
}
zle -N toggle_sudo
bindkey '^S' toggle_sudo
bindkey "^H" backward-kill-word

# pnpm
export PNPM_HOME="/home/joel/.local/share/pnpm"
case ":$PATH:" in
  *":$PNPM_HOME:"*) ;;
  *) export PATH="$PNPM_HOME:$PATH" ;;
esac
# pnpm end

# bun completions
[ -s "/home/joel/.bun/_bun" ] && source "/home/joel/.bun/_bun"

# bun
export BUN_INSTALL="$HOME/.bun"
export PATH="$BUN_INSTALL/bin:$PATH"
